### Import the libraries required for data loading, cleaning, analysis, visualization,
### and statistical modeling.

In [2]:
import matplotlib
import numpy as np
import pandas as pd
import scipy
import seaborn as sns
import statsmodels

In [3]:
df_raw=pd.read_csv("../data/raw/ecommerce_sales_data.csv",dtype=str,keep_default_na=False)

In [4]:
df = df_raw.copy(deep=True)

In [5]:
df.head()

,Order ID,Customer_ID,Order Date,Category,Product Name,Qty,Unit Price,Country,PaymentMethod,customer_email,Rating,Discount,Returned?
0,ORD1031,CUST114,2023/04/22,Clothing,Shampoo,1,,Australia,Credit Card,customer27@mail.com,2,,No
1,ORD1109,CUST33,30.06.2023,Beauty,,10,free,France,PayPal,customer80@mail.com,5,0.41,
2,ORD1136,CUST5,2024/02/16,beauty,T-Shirt,8,28.03,INDIA,paypal,customer111@mail.com,1,0.1,Yes
3,ORD1088,CUST188,19-Sep-2024,Clothing,T-Shirt,9,111.45,Australia,Credit Card,customer166@mail.com,4,13%,Yes
4,ORD1920,CUST75,2024-04-21,beauty,Bluetooth Speaker,1,199.25,Germany,paypal,customer63@mail.com,2,16%,Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031 entries, 0 to 1030
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        1031 non-null   object
 1   Customer_ID     1031 non-null   object
 2     Order Date    1031 non-null   object
 3   Category        1031 non-null   object
 4   Product Name    1031 non-null   object
 5   Qty             1031 non-null   object
 6   Unit Price      1031 non-null   object
 7   Country         1031 non-null   object
 8   PaymentMethod   1031 non-null   object
 9   customer_email  1031 non-null   object
 10  Rating          1031 non-null   object
 11  Discount        1031 non-null   object
 12  Returned?       1031 non-null   object
dtypes: object(13)
memory usage: 104.8+ KB

In [7]:
df.shape

(1031, 13)

In [8]:
df.columns = df.columns.str.strip()

In [9]:
empty_rows = ((df == "") | (df.isna())).all(axis=1)
df.index[empty_rows].tolist()

[159]

In [10]:
disguised_markers = ['', 'na', 'n/a', 'unknown', 'invalid_date', 'nan']
list_of_all_column=[column_name for column_name in df.columns]

In [11]:
missing_summary = []
for correct_column in list_of_all_column:
     null_count = df[correct_column].isna().sum()
     cleaned_values = (
        df[correct_column]
        .astype("string")
        .str.strip()
        .str.lower()
     )
     disguised_count = cleaned_values.isin(disguised_markers).sum()
     total_missing = null_count + disguised_count
     missing_percentage=(total_missing/len(df))*100
     missing_summary.append({
        "Column": correct_column,
        "Total Missing": total_missing,
        "Missing Percentage": missing_percentage
     })

In [12]:
missing_summary

[{'Column': 'Order ID',
  'Total Missing': np.int64(1),
  'Missing Percentage': np.float64(0.09699321047526674)},
 {'Column': 'Customer_ID',
  'Total Missing': np.int64(34),
  'Missing Percentage': np.float64(3.2977691561590685)},
 {'Column': 'Order Date',
  'Total Missing': np.int64(34),
  'Missing Percentage': np.float64(3.2977691561590685)},
 {'Column': 'Category',
  'Total Missing': np.int64(1),
  'Missing Percentage': np.float64(0.09699321047526674)},
 {'Column': 'Product Name',
  'Total Missing': np.int64(93),
  'Missing Percentage': np.float64(9.020368574199807)},
 {'Column': 'Qty',
  'Total Missing': np.int64(39),
  'Missing Percentage': np.float64(3.7827352085354025)},
 {'Column': 'Unit Price',
  'Total Missing': np.int64(26),
  'Missing Percentage': np.float64(2.521823472356935)},
 {'Column': 'Country',
  'Total Missing': np.int64(194),
  'Missing Percentage': np.float64(18.816682832201746)},
 {'Column': 'PaymentMethod',
  'Total Missing': np.int64(233),
  'Missing Percentage': np.float64(22.59941804073715)},
 {'Column': 'customer_email',
  'Total Missing': np.int64(103),
  'Missing Percentage': np.float64(9.990300678952474)},
 {'Column': 'Rating',
  'Total Missing': np.int64(62),
  'Missing Percentage': np.float64(6.0135790494665375)},
 {'Column': 'Discount',
  'Total Missing': np.int64(124),
  'Missing Percentage': np.float64(12.027158098933075)},
 {'Column': 'Returned?',
  'Total Missing': np.int64(29),
  'Missing Percentage': np.float64(2.8128031037827355)}]

In [13]:
duplicate_mask = df.duplicated(keep=False)
duplicate_count = duplicate_mask.sum()
duplicate_count

np.int64(36)

In [14]:
order_id_duplicate_mask = df.duplicated(
    subset=["Order ID"],
    keep=False
)
df[order_id_duplicate_mask].sort_values(by="Order ID")

,Order ID,Customer_ID,Order Date,Category,Product Name,Qty,Unit Price,Country,PaymentMethod,customer_email,Rating,Discount,Returned?
286,ORD1003,CUST274,09.05.2023,Books,wireless mouse,9,81.51,USA,COD,customer107@mail.com,1,,Yes
84,ORD1003,CUST297,04-06-2023,Electronics,Phone Case,8,60.5,France,Credit Card,customer253@mail.com,,0.06,1
414,ORD1006,CUST275,2023-01-27,ELECTRONICS,Smart Watch,10,76010.0,,COD,customer176@mail.com,4,0.08,True
98,ORD1006,CUST275,2023-01-27,ELECTRONICS,Smart Watch,10,76010.0,,COD,customer176@mail.com,4,0.08,True
307,ORD1009,CUST103,10-13-2024,Books,Running Shoes,2,146.34,U.S.A,Credit Card,customer75@mail.com,5,0.33,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,ORD1954,CUST24,29-Mar-2023,Clothing,Running Shoes,10,163.42,,PayPal,customer6@mail.com,4,0.49,Yes
603,ORD1968,CUST166,07/01/2023,Home & Kitchen,,9,$199.86,india,,customer234@mail.com,2,5%,Yes
687,ORD1968,CUST166,07/01/2023,Home & Kitchen,,9,$199.86,india,,customer234@mail.com,2,5%,Yes
966,ORD1971,CUST265,02.01.2024,Books,Laptop Stand,6,73.62,USA,Cash on Delivery,customer37@mail.com,3,0.02,No
37,ORD1971,CUST265,02.01.2024,Books,Laptop Stand,6,73.62,USA,Cash on Delivery,customer37@mail.com,3,0.02,No

In [15]:
# Check the unique values and their frequency in important categorical columns.

categorical_columns = [
    "Category",
    "Product Name",
    "Country",
    "PaymentMethod",
    "Returned?"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Category ---
Category
ELECTRONICS             90
Electronics             87
beauty                  81
Clothing                79
electronics             79
Home & Kitchen          76
Books                   75
Sports                  74
Beauty                  72
Home and Kitchen        71
Books                   69
clothing                58
  Home & Kitchen        13
  clothing              13
  Electronics           12
  Home and Kitchen      12
  electronics           12
  beauty                11
  Sports                10
  Books                  9
  Books                  8
  Clothing               7
  Beauty                 7
  ELECTRONICS            5
                         1
Name: count, dtype: int64

--- Product Name ---
Product Name
                         93
Notebook                 56
USB-C Cable              56
Denim Jacket             53
Headphones               52
T-Shirt                  52
Bluetooth Speaker        49
Face Cream               48
Shampoo                  47
Smart Watch              47
Wireless Mouse           47
Phone Case               47
Power Bank               45
Yoga Mat                 44
Laptop Stand             43
Gel Pen                  42
 Running Shoes           40
Webcam HD                39
wireless mouse           34
  Power Bank             10
  Webcam HD               9
  Bluetooth Speaker       7
  Shampoo                 7
  wireless mouse          7
  Gel Pen                 6
  Face Cream              6
   Running Shoes          6
  Laptop Stand            6
  T-Shirt                 5
  Yoga Mat                5
  Headphones              5
  Smart Watch             5
  Wireless Mouse          4
  Denim Jacket            4
  USB-C Cable             2
  Notebook                2
  Phone Case              1
Name: count, dtype: int64

--- Country ---
Country
Australia             76
                      65
India                 64
Germany               63
UK                    63
N/A                   63
 France               62
United Kingdom        60
United States         58
USA                   58
U.S.A                 57
INDIA                 56
unknown               55
France                52
india                 51
germany               44
  UK                  12
  Germany              8
  USA                  7
  U.S.A                7
  France               7
  United Kingdom       6
  India                6
  N/A                  6
  unknown              5
   France              5
  United States        5
  Australia            4
  INDIA                3
  india                2
  germany              1
Name: count, dtype: int64

--- PaymentMethod ---
PaymentMethod
                        139
paypal                   81
CREDIT CARD              81
Credit Card              74
UPI                      74
NA                       72
credit card              71
PayPal                   70
COD                      68
Debit Card               66
Cash on Delivery         66
upi                      60
                         13
  upi                    12
  Debit Card             12
  COD                    11
  Cash on Delivery       10
  Credit Card             9
  NA                      9
  PayPal                  9
  paypal                  7
  credit card             6
  UPI                     6
  CREDIT CARD             5
Name: count, dtype: int64

--- Returned? ---
Returned?
No       397
Yes      384
1         32
True      31
no        30
          29
N         29
yes       28
0         27
False     24
Y         20
Name: count, dtype: int64

In [16]:
# Display all unique values for each categorical column.

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].unique())

--- Category ---
['Clothing' 'Beauty' 'beauty ' 'ELECTRONICS' 'Electronics' 'clothing'
 '  Electronics  ' 'Books ' 'electronics' '  Clothing  '
 'Home and Kitchen' 'Books' 'Sports' '  Home & Kitchen  ' 'Home & Kitchen'
 '  Books  ' '  Books   ' '  Sports  ' '  Home and Kitchen  '
 '  clothing  ' '  beauty   ' '  ELECTRONICS  ' '' '  electronics  '
 '  Beauty  ']

--- Product Name ---
['Shampoo' '' 'T-Shirt' 'Bluetooth Speaker' 'Headphones' 'Yoga Mat'
 'wireless mouse' 'Smart Watch ' '  Power Bank  ' 'USB-C Cable'
 'Power Bank' 'Denim Jacket' ' Running Shoes' 'Wireless Mouse'
 '  Gel Pen  ' 'Notebook' 'Gel Pen' 'Face Cream' 'Laptop Stand'
 'Webcam HD' '  Face Cream  ' '   Running Shoes  ' 'Phone Case'
 '  Webcam HD  ' '  wireless mouse  ' '  T-Shirt  ' '  Wireless Mouse  '
 '  Headphones  ' '  Shampoo  ' '  Denim Jacket  ' '  Yoga Mat  '
 '  Laptop Stand  ' '  Bluetooth Speaker  ' '  Smart Watch   '
 '  USB-C Cable  ' '  Notebook  ' '  Phone Case  ']

--- Country ---
['Australia' 'France' 'INDIA' 'Germany' 'india' '' 'U.S.A'
 'United Kingdom' 'unknown' 'germany' ' France' 'India' '  unknown  '
 '  USA  ' 'USA' 'UK' 'N/A' 'United States' '  United States  '
 '  Germany  ' '  Australia  ' '  India  ' '  France  '
 '  United Kingdom  ' '  UK  ' '  N/A  ' '  U.S.A  ' '  INDIA  '
 '   France  ' '  india  ' '  germany  ']

--- PaymentMethod ---
['Credit Card' 'PayPal' '  paypal  ' 'paypal' 'COD' '' 'NA'
 '  CREDIT CARD  ' 'upi' 'UPI' 'CREDIT CARD' 'credit card' '  upi  '
 '  PayPal  ' 'Cash on Delivery' 'Debit Card' '    ' '  credit card  '
 '  Cash on Delivery  ' '  Credit Card  ' '  UPI  ' '  NA  ' '  COD  '
 '  Debit Card  ']

--- Returned? ---
['No' '' 'Yes' 'no' 'N' '0' '1' 'True' 'yes' 'False' 'Y']

In [17]:
# Count invalid emails containing '@@'.

invalid_email_count = df["customer_email"].str.contains(
    "@@",
    na=False
).sum()

print("Invalid emails containing '@@':", invalid_email_count)

Invalid emails containing '@@': 46

In [18]:
# Create a cross-frequency table between Category and Product Name.
# strip() removes extra spaces and lower() makes the comparison case-insensitive.

category_product_table = pd.crosstab(
    df["Category"].str.strip().str.lower(),
    df["Product Name"].str.strip().str.lower()
)

category_product_table

Product Name,,bluetooth speaker,denim jacket,face cream,gel pen,headphones,laptop stand,notebook,phone case,power bank,running shoes,shampoo,smart watch,t-shirt,usb-c cable,webcam hd,wireless mouse,yoga mat
Category,,,,,,,,,,,,,,,,,,
,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
beauty,21,12,8,14,10,7,6,8,5,10,3,6,11,10,7,11,15,7
books,12,7,8,13,9,7,7,8,8,11,8,7,6,7,8,9,19,7
clothing,10,8,8,5,6,8,7,8,7,8,11,7,9,9,15,8,11,12
electronics,24,17,18,9,16,20,15,18,20,11,14,19,12,11,16,12,22,11
home & kitchen,9,4,4,4,1,3,9,4,4,6,7,4,4,7,5,2,10,2
home and kitchen,12,3,5,3,2,8,2,5,4,5,0,3,6,8,1,2,9,5
sports,4,5,6,6,4,4,3,7,0,4,3,8,4,5,6,4,6,5

In [19]:
Numeric_Columns=['Qty', 'Unit Price', 'Rating', 'Discount']
for col in Numeric_Columns:
    df[col]=pd.to_numeric(df[col], errors='coerce')
    invalid_values=df[col][pd.to_numeric(df[col], errors='coerce').isna() & (df[col] != "")]
    print(f"\n{'=' * 50}")
    print(f"Non-convertible values in: {col}")
    print(f"{'=' * 50}")

    print(invalid_values)

==================================================
Non-convertible values in: Qty
==================================================
11     NaN
16     NaN
20     NaN
33     NaN
34     NaN
        ..
976    NaN
980    NaN
1001   NaN
1019   NaN
1028   NaN
Name: Qty, Length: 61, dtype: float64

==================================================
Non-convertible values in: Unit Price
==================================================
0      NaN
1      NaN
12     NaN
15     NaN
27     NaN
        ..
993    NaN
997    NaN
1004   NaN
1027   NaN
1030   NaN
Name: Unit Price, Length: 132, dtype: float64

==================================================
Non-convertible values in: Rating
==================================================
14    NaN
17    NaN
24    NaN
46    NaN
76    NaN
       ..
981   NaN
982   NaN
988   NaN
989   NaN
992   NaN
Name: Rating, Length: 86, dtype: float64

==================================================
Non-convertible values in: Discount
==================================================
0      NaN
3      NaN
4      NaN
7      NaN
9      NaN
        ..
1020   NaN
1022   NaN
1025   NaN
1029   NaN
1030   NaN
Name: Discount, Length: 419, dtype: float64

In [20]:
# --------------------------------------------------
# HINT 3: Check invalid_date string
# --------------------------------------------------

invalid_date_count = (
    df['Order Date']
    .astype(str)
    .str.strip()
    .eq('invalid_date')
    .sum()
)

print("Number of 'invalid_date' values:", invalid_date_count)

Number of 'invalid_date' values: 14

In [21]:
# --------------------------------------------------
# Try converting Order Date into datetime
# --------------------------------------------------

parsed_dates = pd.to_datetime(
    df['Order Date'].astype(str).str.strip(),
    errors='coerce'
)

print("Successfully parsed dates:", parsed_dates.notna().sum())
print("Failed to parse dates:", parsed_dates.isna().sum())

Successfully parsed dates: 156
Failed to parse dates: 875

In [22]:
# --------------------------------------------------
# Display invalid/unparseable dates
# --------------------------------------------------

invalid_dates = df[
    parsed_dates.isna()
]

print("Invalid / Unparseable dates:")
print(invalid_dates[['Order Date']])

Invalid / Unparseable dates:
       Order Date
1      30.06.2023
3     19-Sep-2024
4      2024-04-21
5      06-11-2023
7     16-May-2024
...           ...
1025   2024-09-16
1027   2023-07-22
1028   27.03.2024
1029   2023-06-28
1030  12-Mar-2024

[875 rows x 1 columns]

In [ ]:
import pandas as pd


numeric_cols = ['Qty', 'Unit Price', 'Rating', 'Discount']

for col in numeric_cols:
    converted = pd.to_numeric(df[col], errors='coerce')

    invalid_values = df[col][
        converted.isna() & (df[col] != "")
    ]

    print(f"\nNon-convertible values in '{col}':")
    print(invalid_values)




for col in numeric_cols:
    converted = pd.to_numeric(df[col], errors='coerce')

    print(f"\n--- {col} ---")
    print("Min:", converted.min())
    print("Max:", converted.max())



qty = pd.to_numeric(df['Qty'], errors='coerce')

print("\nNegative or Zero Quantity:")
print(df[qty <= 0])



unit_price = pd.to_numeric(df['Unit Price'], errors='coerce')

print("\nNegative Unit Price:")
print(df[unit_price < 0])



rating = pd.to_numeric(df['Rating'], errors='coerce')

print("\nRating greater than 5:")
print(df[rating > 5])



print("\nUnit Price greater than 10000:")
print(df[unit_price > 10000])



print("\nQuantity greater than 100:")
print(df[qty > 100])



invalid_date_count = (
    df['Order Date'].astype(str).str.strip() == 'invalid_date'
).sum()

print("\nCount of 'invalid_date':", invalid_date_count)



converted_dates = pd.to_datetime(
    df['Order Date'].str.strip(),
    errors='coerce'
)

print("\nParsed dates:")
print(converted_dates)



print("\nSuccessfully parsed dates:",
      converted_dates.notna().sum())


print("Failed to parse dates:",
      converted_dates.isna().sum())

Non-convertible values in 'Qty':
11     NaN
16     NaN
20     NaN
33     NaN
34     NaN
        ..
976    NaN
980    NaN
1001   NaN
1019   NaN
1028   NaN
Name: Qty, Length: 61, dtype: float64

Non-convertible values in 'Unit Price':
0      NaN
1      NaN
12     NaN
15     NaN
27     NaN
        ..
993    NaN
997    NaN
1004   NaN
1027   NaN
1030   NaN
Name: Unit Price, Length: 132, dtype: float64

Non-convertible values in 'Rating':
14    NaN
17    NaN
24    NaN
46    NaN
76    NaN
       ..
981   NaN
982   NaN
988   NaN
989   NaN
992   NaN
Name: Rating, Length: 86, dtype: float64

Non-convertible values in 'Discount':
0      NaN
3      NaN
4      NaN
7      NaN
9      NaN
        ..
1020   NaN
1022   NaN
1025   NaN
1029   NaN
1030   NaN
Name: Discount, Length: 419, dtype: float64

--- Qty ---
Min: -5.0
Max: 9999.0

--- Unit Price ---
Min: -160.93
Max: 187080.0

--- Rating ---
Min: 1.0
Max: 10.0

--- Discount ---
Min: 0.0
Max: 0.5

Negative or Zero Quantity:
     Order ID Customer_ID   Order Date        Category    Product Name  Qty  \
15    ORD1584      CUST64   10.12.2023         beauty       Power Bank -5.0
32    ORD1721     CUST239   22.01.2023          Beauty        Yoga Mat  0.0
77    ORD1328     CUST274   23.04.2024     ELECTRONICS        Notebook -2.0
111   ORD1307     CUST177   03-14-2023          Beauty      Face Cream -1.0
112   ORD1067      CUST21   2024/02/20     electronics  Wireless Mouse  0.0
...       ...         ...          ...             ...             ...  ...
961   ORD1871      CUST11  20-Mar-2024     electronics      Phone Case -5.0
987   ORD1504     CUST198   2024/05/15     ELECTRONICS    Smart Watch   0.0
1008  ORD1252     CUST239   18/09/2024     ELECTRONICS         Gel Pen -3.0
1011  ORD1459     CUST118   28.01.2024  Home & Kitchen        Yoga Mat -2.0
1022  ORD1308       CUST3   2024-05-27          Sports     USB-C Cable -4.0

      Unit Price         Country     PaymentMethod        customer_email  \
15           NaN         Germany       CREDIT CARD
32           NaN              UK  Cash on Delivery   customer40@mail.com
77         80.09  United Kingdom               upi  customer191@mail.com
111       118.03              UK       Credit Card  customer177@mail.com
112       165.28           india                NA   customer76@mail.com
...          ...             ...               ...                   ...
961        78.20   United States            PayPal   customer18@mail.com
987       158.41         Germany                    customer165@mail.com
1008      173.35       Germany                       customer50@mail.com
1011       15.30           India               UPI
1022      194.93         unknown               upi  customer232@mail.com

      Rating  Discount Returned?
15       2.0      0.13       Yes
32       5.0       NaN        No
77       1.0      0.31
111      2.0       NaN        No
112      5.0      0.04
...      ...       ...       ...
961      3.0       NaN       Yes
987      1.0      0.01       Yes
1008     1.0       NaN        No
1011     4.0      0.12        No
1022     1.0       NaN        No

[61 rows x 13 columns]

Negative Unit Price:
    Order ID Customer_ID   Order Date              Category  \
25   ORD1321      CUST92   29/04/2023      Home and Kitchen
47   ORD1622     CUST190   2024/10/06                 Books
68   ORD1192     CUST130   04-05-2024    Home and Kitchen
91   ORD1174      CUST38   26.04.2023                Books
148  ORD1932      CUST85   2023-07-25        Home & Kitchen
292  ORD1445      CUST11   2024/03/26                 Books
354  ORD1212      CUST24  10-Aug-2024      Home and Kitchen
449  ORD1877               2024/07/09      Home & Kitchen
491  ORD1486      CUST61   11-12-2024               beauty
513  ORD1585     CUST116   02-22-2023         electronics
525  ORD1167     CUST113   23.07.2024           Electronics
533  ORD1257     CUST134  20-Jun-2024                Sports
630  ORD1322      CUST78   2023-01-07                Books
650  ORD1777      CUST92   19.02.2023                Sports
669  ORD1364     CUST261  04-Mar-2023                Beauty
699  ORD1421      CUST36  17-Oct-2023           electronics
714  ORD1008      CUST15   18.07.2023                Books
741  ORD1972     CUST247  24-Jul-2024        Home & Kitchen
750  ORD1608     CUST219   21.06.2024              Books
772  ORD1402     CUST259   17/01/2023           ELECTRONICS
802  ORD1233      CUST28   2024/09/05                Beauty
866  ORD1397     CUST122   2023/01/10           ELECTRONICS
925  ORD1052     CUST103   2024-11-11                Books
935  ORD1461     CUST207  14-Dec-2023                 Books
971  ORD1564     CUST165   2024/09/02             beauty
992  ORD1562     CUST163   2023-07-05           Electronics

          Product Name     Qty  Unit Price      Country     PaymentMethod  \
25            Notebook     5.0     -159.66        USA               upi
47          Face Cream     6.0      -93.88        India     credit card
68        Denim Jacket     6.0     -125.66      unknown     credit card
91        Smart Watch      8.0      -39.69      germany  Cash on Delivery
148      Running Shoes     9.0      -70.88       France       credit card
292         Phone Case     2.0      -71.05           UK            paypal
354     Wireless Mouse  9999.0     -156.53    Germany         credit card
449           Yoga Mat     8.0     -100.35    Australia            paypal
491          Webcam HD    10.0      -21.74    Australia            paypal
513       Laptop Stand    10.0      -28.62      germany            PayPal
525       Laptop Stand     8.0     -152.64          USA     CREDIT CARD
533            T-Shirt    10.0      -39.18        U.S.A        Debit Card
630         Headphones    10.0      -60.43      germany            paypal
650            T-Shirt     1.0      -60.84      unknown                NA
669     Wireless Mouse     1.0     -137.61    Germany    Cash on Delivery
699     wireless mouse     3.0     -138.68          N/A
714       Denim Jacket     6.0      -20.70                     Debit Card
741      Running Shoes     3.0     -142.43                    credit card
750     wireless mouse     5.0      -40.11          N/A            PayPal
772  Bluetooth Speaker     9.0     -122.27           UK            paypal
802            Gel Pen     3.0     -160.93      Germany                NA
866            Shampoo     5.0      -43.05          USA               UPI
925      Running Shoes     NaN      -45.12        india                NA
935       Laptop Stand     4.0     -129.88                    credit card
971                        6.0      -41.64    Australia
992       Denim Jacket     7.0     -115.28        INDIA       CREDIT CARD

           customer_email  Rating  Discount Returned?
25   customer245@mail.com     2.0      0.06       Yes
47   customer131@mail.com     2.0      0.01        No
68   CUSTOMER286@MAIL.COM     4.0      0.02        No
91    customer49@mail.com     4.0       NaN       Yes
148  CUSTOMER210@MAIL.COM     4.0      0.41        No
292  customer189@mail.com     1.0      0.44         1
354  customer132@mail.com     NaN      0.18         Y
449                           1.0      0.22        No
491  customer138@mail.com     3.0       NaN         0
513   customer73@mail.com     5.0       NaN       Yes
525  customer166@mail.com     NaN      0.44       Yes
533  customer171@mail.com     4.0      0.02       Yes
630  customer123@mail.com     5.0      0.29        No
650  customer257@mail.com     2.0       NaN       Yes
669  customer151@mail.com     2.0      0.19        No
699  customer178@mail.com     4.0       NaN        No
714    customer1@mail.com     3.0      0.04        No
741  customer178@mail.com     3.0      0.28       Yes
750   customer59@mail.com     6.0      0.27        No
772   customer84@mail.com     4.0       NaN       yes
802   customer47@mail.com     2.0      0.03       Yes
866   customer89@mail.com     1.0       NaN        No
925  customer148@mail.com     2.0       NaN        No
935   customer45@mail.com     4.0       NaN        No
971  customer212@mail.com     5.0       NaN        No
992  customer155@mail.com     NaN      0.37       Yes

Rating greater than 5:
    Order ID Customer_ID   Order Date              Category  \
36   ORD1256      CUST11   2024/05/11               beauty
94   ORD1368     CUST102   28/04/2023              Sports
97   ORD1231      CUST59   2024-11-26           Electronics
216  ORD1899     CUST193   10-06-2023      Home and Kitchen
223  ORD1997     CUST218  16-Mar-2023           ELECTRONICS
225  ORD1580     CUST130   19.02.2024      Home and Kitchen
248  ORD1065     CUST239   2024-11-23                 Books
256  ORD1695      CUST72   04-30-2024        Home & Kitchen
278  ORD1082      CUST34   2023/02/26                 Books
326  ORD1976     CUST170   2024/05/29           electronics
333  ORD1155     CUST244  24-Mar-2024      Home and Kitchen
348  ORD1739     CUST211   04.02.2024              Sports
358  ORD1448     CUST145  29-Jun-2024               beauty
364  ORD1133     CUST229   04.05.2024           ELECTRONICS
395  ORD1605      CUST78  01-Apr-2024        Home & Kitchen
396  ORD1068       CUST6   06-29-2023           electronics
399  ORD1662      CUST62   11-12-2023      Home & Kitchen
410  ORD1169      CUST57   06-16-2024              Clothing
417  ORD1679     cust286   12/11/2024              clothing
434  ORD1041      CUST23   2023/02/24                Books
452  ORD1051     CUST158   2024-08-22           Electronics
456  ORD1502     CUST155  14-May-2024                Books
483  ORD1368     CUST102   28/04/2023              Sports
486  ORD1223     CUST108                           Clothing
489  ORD1707      CUST89   23.09.2024      Home and Kitchen
496  ORD1696     CUST234   15/07/2024           electronics
524  ORD1042      cust99   2024-11-19      Home and Kitchen
539  ORD1222      CUST80   19.04.2023                Sports
557  ORD1284       CUST4   2024-08-09      Home and Kitchen
573  ORD1829     CUST162   20/06/2024                Beauty
628  ORD1017     CUST176   13/10/2024           Electronics
638  ORD1180     CUST189   2023-08-21           electronics
655  ORD1133     CUST229   04.05.2024           ELECTRONICS
663  ORD1684     CUST279   2023-06-27              Clothing
719  ORD1253      CUST98   11/03/2024                Books
738  ORD1147     CUST211   08/09/2023           ELECTRONICS
750  ORD1608     CUST219   21.06.2024              Books
751  ORD1143     CUST180   08/01/2024         electronics
755  ORD1609     CUST158   2024/02/19                Beauty
762  ORD1438      cust65  15-Jul-2024         electronics
779  ORD1953     CUST109   19.06.2024        Home & Kitchen
793  ORD1112     CUST264   2024/02/06                Sports
803  ORD1984      CUST76   2024-03-06           Electronics
811  ORD1258      CUST39   07.05.2024    Home and Kitchen
819  ORD1996     CUST212   20.07.2024           Electronics
829  ORD1619      CUST18   2024/06/03               beauty
882  ORD1727     CUST114   09-17-2023                Books
885  ORD1502     CUST155  14-May-2024              Books
904  ORD1138     CUST277   23/02/2023                Beauty
908  ORD1057     CUST277   2024-05-27           electronics
920  ORD1187              01-Jul-2024           electronics
928  ORD1748     CUST187   2023-01-23             beauty
999  ORD1699     CUST253   03.05.2024           electronics

           Product Name     Qty  Unit Price         Country     PaymentMethod  \
36           Face Cream     7.0         NaN          France            paypal
94           Face Cream     3.0      154.10           India        Debit Card
97                         10.0         NaN  United Kingdom        Debit Card
216                        -4.0      185.79       Australia       Credit Card
223      wireless mouse     7.0      104.32          France               COD
225        Denim Jacket     7.0       69.66         germany       credit card
248      Wireless Mouse    -1.0      138.10          France                NA
256          Power Bank     4.0       16.69             N/A               upi
278             Shampoo     NaN       84.86           U.S.A
326          Face Cream     4.0      102.85          France             COD
333             T-Shirt     8.0       57.04         unknown            PayPal
348         Webcam HD       6.0      140.62           INDIA     Credit Card
358                         9.0       98.85          France       credit card
364      Wireless Mouse     6.0      100.31        France              PayPal
395                         NaN   110110.00       Australia            paypal
396         USB-C Cable     4.0      114.64           India       CREDIT CARD
399        Laptop Stand     NaN       22.41          France       credit card
410         USB-C Cable  9999.0       58.43         germany     CREDIT CARD
417          Headphones     6.0       35.88              UK       Credit Card
434                         3.0      129.86       Australia            paypal
452      Wireless Mouse     NaN         NaN           U.S.A
456       Running Shoes     6.0      143.23  United Kingdom  Cash on Delivery
483          Face Cream     3.0      154.10           India        Debit Card
486       Running Shoes     NaN       84.55         germany               upi
489          Headphones     9.0        7.27  United Kingdom       Credit Card
496             T-Shirt     6.0      182.45  United Kingdom               COD
524                         5.0      131.56  United Kingdom  Cash on Delivery
539      wireless mouse     3.0      164.65         germany            PayPal
557   Bluetooth Speaker     9.0      106.27         U.S.A    Cash on Delivery
573                         4.0      115.82         U.S.A                 UPI
628        Laptop Stand    -3.0         NaN       Australia            PayPal
638          Face Cream     1.0       60.61              UK             UPI
655      Wireless Mouse     6.0      100.31          France            PayPal
663             T-Shirt     NaN         NaN          France            paypal
719          Phone Case    10.0       82.96       Australia       CREDIT CARD
738        Denim Jacket     4.0       43.65          France
750      wireless mouse     5.0      -40.11             N/A            PayPal
751             Gel Pen     9.0         NaN       Australia               COD
755            Notebook     9.0      169.94           India      Debit Card
762           Webcam HD     4.0       60.58           U.S.A  Cash on Delivery
779      wireless mouse     3.0         NaN       Germany              paypal
793             Shampoo     3.0       77.81       Australia      Debit Card
803           Webcam HD     6.0       48.20       Australia       CREDIT CARD
811          Headphones     1.0      119.33         germany
819        Smart Watch      7.0      117.21         Germany               upi
829            Yoga Mat     4.0      155.75              UK               COD
882            Yoga Mat     9.0       82.76           U.S.A               UPI
885       Running Shoes     6.0      143.23  United Kingdom  Cash on Delivery
904           Shampoo       3.0       76.32              UK               COD
908        Denim Jacket     4.0      147.62   United States       Credit Card
920    Wireless Mouse       2.0         NaN  United Kingdom       CREDIT CARD
928             Gel Pen     9.0       41.52           INDIA               UPI
999             T-Shirt     8.0       94.69           U.S.A  Cash on Delivery

           customer_email  Rating  Discount Returned?
36   customer167@mail.com    10.0       NaN         N
94   customer232@mail.com    10.0       NaN        No
97    customer63@mail.com     8.0      0.43         0
216   customer49@mail.com     7.0      0.14        no
223  customer145@mail.com    10.0      0.22       Yes
225                          10.0       NaN         1
248   customer74@mail.com     9.0      0.17        No
256   customer38@mail.com     8.0       NaN       Yes
278  customer188@mail.com     8.0      0.43        No
326  customer281@mail.com     7.0      0.17        No
333  customer162@mail.com     8.0      0.24        No
348  customer12@@mail.com     6.0      0.12       Yes
358  customer146@mail.com    10.0      0.29      True
364  CUSTOMER103@MAIL.COM     8.0       NaN        No
395  customer207@mail.com     8.0      0.27     False
396  customer265@mail.com     6.0       NaN        No
399  customer226@mail.com     7.0      0.07       Yes
410   customer99@mail.com     6.0       NaN       Yes
417  customer263@mail.com     8.0      0.29       Yes
434  customer112@mail.com    10.0       NaN        no
452                           6.0      0.37     False
456  customer278@mail.com     6.0      0.41         N
483  customer232@mail.com    10.0       NaN        No
486  customer114@mail.com     9.0      0.22        No
489  customer228@mail.com     6.0       NaN        No
496   customer50@mail.com     9.0       NaN        No
524   customer92@mail.com    10.0      0.23        No
539                          10.0      0.36       Yes
557  customer226@mail.com     6.0       NaN       Yes
573  customer291@mail.com     8.0       NaN         1
628  customer151@mail.com     7.0       NaN         N
638  customer206@mail.com     7.0       NaN         0
655  CUSTOMER103@MAIL.COM     8.0       NaN        No
663   customer78@mail.com    10.0      0.08        No
719  customer239@mail.com     6.0       NaN      True
738  customer246@mail.com    10.0      0.45       Yes
750   customer59@mail.com     6.0      0.27        No
751                          10.0       NaN        No
755  customer207@mail.com    10.0       NaN       Yes
762  customer257@mail.com    10.0      0.05        No
779  customer145@mail.com    10.0      0.16       yes
793                          10.0      0.23       yes
803  customer204@mail.com     7.0      0.22        No
811  customer259@mail.com     6.0      0.50         N
819   customer66@mail.com     9.0       NaN         1
829  customer256@mail.com    10.0      0.50       Yes
882  customer281@mail.com    10.0      0.13       Yes
885  customer278@mail.com     6.0      0.41         N
904  customer161@mail.com     6.0      0.28        No
908  CUSTOMER261@MAIL.COM    10.0      0.13       Yes
920   customer10@mail.com     6.0      0.48         N
928  customer100@mail.com     9.0       NaN        No
999  customer46@@mail.com     8.0      0.45        No

Unit Price greater than 10000:
    Order ID Customer_ID   Order Date          Category        Product Name  \
59   ORD1591     CUST110  21-Oct-2023  Home and Kitchen
98   ORD1006     CUST275   2023-01-27       ELECTRONICS        Smart Watch
183  ORD1764     CUST143   15/06/2023          Clothing           Webcam HD
272  ORD1359     CUST167   01/07/2023     electronics        Wireless Mouse
395  ORD1605      CUST78  01-Apr-2024    Home & Kitchen
414  ORD1006     CUST275   2023-01-27       ELECTRONICS        Smart Watch
425  ORD1220     CUST188   01-14-2024       ELECTRONICS        Laptop Stand
484  ORD1527     CUST267   04.05.2023            Books
612  ORD1843     CUST195   04-29-2024       electronics        Denim Jacket
623  ORD1154     CUST195   04.01.2024            Sports             Shampoo
723  ORD1623     CUST226   05-28-2024         beauty
729  ORD1414     CUST249   12.07.2024    Home & Kitchen      Wireless Mouse
757  ORD1030      CUST95   2023/04/22  Home and Kitchen      Laptop Stand
785  ORD1793     CUST159   27/08/2023           Books          Smart Watch
791  ORD1441      CUST10   29/02/2024            Sports          Power Bank
808  ORD1936      CUST45   2023-10-12    Home & Kitchen    Wireless Mouse
846  ORD1170     CUST234   11.08.2024       electronics      Wireless Mouse

      Qty  Unit Price         Country     PaymentMethod        customer_email  \
59    5.0    176060.0           india            paypal  customer211@mail.com